# Generated by Django 5.0 on 2025-02-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_form_info',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
